version: "3"

services:
  # データベース
  db:
    image: mysql:8.0
    container_name: t3stack
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: t3stack
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/t3stack/mysql/data
      - ./my.cnf:/etc/mysql/my.cnf
